name: AuthMePE
version: '1.1.1'
main: me.shinthl09.AuthMePE
api-version: 1.13
depend: [ Geyser-Spigot , AuthMe]
author: ShinTHL09
editor: ItzMintDzX
commands:
  authmepe:
    usage: /<command>
    description: "AuthMePE Command"
    aliases: [ athpe ]
permissions:
  authmepe.admin:
    description: "Permissions Cho Admin"
    default: op
