name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt-get update
        sudo apt-get install gh

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: |
        mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        JAR_FILE=$(find $GITHUB_WORKSPACE/target -name "*.jar")
        gh release create ${{ github.sha }} $JAR_FILE -t "Release ${{ github.sha }}" -n "Release notes go here" --notes "Release notes go here"
      env:
        GITHUB_TOKEN: ${{ github.token }}
